vhdl-sources += adv7511.pkg.vhd
vhdl-sources += adv7511_driver.vhd

deps += nsl_bnoc.framed
deps += nsl_data.bytestream
deps += nsl_i2c.transactor
deps += nsl_io.ddr
deps += nsl_io.diff
deps += nsl_math.arith
deps += nsl_synthesis.assertion
deps += nsl_video.pixel_stream
deps += nsl_video.raster
