vhdl-sources += tb.vhd

deps += nsl_amba.axi4_mm
deps += nsl_amba.mm_routing
deps += nsl_amba.address
deps += nsl_amba.ram
deps += nsl_simulation.driver
deps += nsl_simulation.logging
deps += nsl_simulation.assertions
