vhdl-sources += mm_routing.pkg.vhd
vhdl-sources += crossbar.pkg.priv.vhd
vhdl-sources += axi4_mm_error_slave.vhd
vhdl-sources += axi4_mm_crossbar_slave_port.vhd
vhdl-sources += axi4_mm_crossbar_master_port.vhd
vhdl-sources += axi4_mm_crossbar.vhd
vhdl-sources += axi4_mm_shared_bus.vhd

deps += nsl_amba.axi4_mm
deps += nsl_amba.address
deps += nsl_data.bytestream
deps += nsl_logic.bool
deps += nsl_math.arith
deps += nsl_memory.fifo
