vhdl-sources += ssd1306.pkg.vhd
vhdl-sources += ssd1306_spi_driver.vhd

deps += nsl_spi.spi
deps += nsl_data.bytestream
deps += nsl_video.pixel_stream
deps += nsl_video.raster
deps += nsl_synthesis.assertion
