library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library nsl_spi, nsl_data, nsl_video;
use nsl_data.bytestream.all;

-- SSD1306 is a 128x64 monochrome OLED panel controller.
--
-- Its display RAM is split in pages of eight lines.  One data byte
-- holds the eight pixels of a column within a page, top line in bit
-- 0.
package ssd1306 is

  constant max_width_c: natural := 128;
  constant max_height_c: natural := 64;
  constant page_height_c: natural := 8;

  -- [Command] [contrast]
  constant cmd_contrast : byte := x"81";
  -- [Command]
  constant cmd_display_normal  : byte := x"a4";
  constant cmd_display_all_on  : byte := x"a5";
  -- [Command]
  constant cmd_display_not_inverted : byte := x"a6";
  constant cmd_display_inverted     : byte := x"a7";
  -- [Command]
  constant cmd_display_sleep : byte := x"ae";
  constant cmd_display_on    : byte := x"af";
  -- [Command] [mode]
  constant cmd_addressing_mode : byte := x"20";
  constant cmd_addressing_mode_horizontal : byte := x"00";
  constant cmd_addressing_mode_vertical   : byte := x"01";
  constant cmd_addressing_mode_page       : byte := x"02";
  -- [Command] [start column] [end column] (inclusive)
  constant cmd_column_address : byte := x"21";
  -- [Command] [start page] [end page] (inclusive)
  constant cmd_page_address : byte := x"22";
  -- [Command | line], line in 0-63
  constant cmd_display_start_line : byte := x"40";
  -- [Command]
  constant cmd_segment_remap_off : byte := x"a0";
  constant cmd_segment_remap_on  : byte := x"a1";
  -- [Command] [ratio minus one], 15 to 63
  constant cmd_multiplex_ratio : byte := x"a8";
  -- [Command]
  constant cmd_com_scan_increasing : byte := x"c0";
  constant cmd_com_scan_decreasing : byte := x"c8";
  -- [Command] [offset]
  constant cmd_display_offset : byte := x"d3";
  -- [Command] [flags]
  constant cmd_com_pins : byte := x"da";
  constant cmd_com_pins_sequential  : byte := x"02";
  constant cmd_com_pins_alternative : byte := x"12";
  constant cmd_com_pins_lr_remap    : byte := x"22";
  -- [Command] [da] oscillator frequency (d), clock divider minus one (a)
  constant cmd_clock_divider : byte := x"d5";
  -- [Command] [ba] phase 2 (b) and phase 1 (a) periods, 0 excluded
  constant cmd_precharge_period : byte := x"d9";
  -- [Command] [level]
  constant cmd_vcomh_deselect_level : byte := x"db";
  -- [Command] [setting]
  constant cmd_charge_pump : byte := x"8d";
  constant cmd_charge_pump_disable : byte := x"10";
  constant cmd_charge_pump_enable  : byte := x"14";

  constant init_sequence_length_c : natural := 24;

  -- Initialization command stream.  Display-on is not part of it: it
  -- should only be sent once display RAM has defined contents and
  -- panel supply is up.
  --
  -- - height selects the multiplex ratio, it must be a multiple of
  --   page_height_c,
  -- - com_alternative selects the COM pin wiring, it depends on the
  --   panel module (sequential for most 128x32, alternative for most
  --   128x64 ones),
  -- - charge_pump selects whether panel supply is generated by the
  --   controller from VBAT, or is externally supplied to VCC,
  -- - rotate_180 mirrors both the segment and the COM scan.  Without
  --   it, column 0 is on SEG127 and line 0 on the last COM, which is
  --   the orientation vendors document for their modules,
  -- - contrast is the segment current setting.
  function init_sequence(height: positive;
                         com_alternative: boolean;
                         charge_pump: boolean;
                         rotate_180: boolean;
                         contrast: byte) return byte_string;

  -- Refreshes the panel from a pixel stream over the serial
  -- interface.
  --
  -- After enable_i is asserted, driver powers the module up (logic
  -- supply, reset, init sequence), streams a first frame, then turns
  -- panel supply on, waits for it to settle, and only then turns the
  -- display on.  It then refreshes the whole panel whenever refresh_i
  -- is asserted while idle.  Deasserting enable_i powers the module
  -- down in order; init and first frame run again on next assertion.
  --
  -- Pixels come in on a stream that states its own framing.  The
  -- driver locks onto the first frame the stream opens and shows its
  -- pixels from there; synced_o states whether it holds.  A stream
  -- with no pixel ready holds the serial interface rather than losing
  -- the pixel.
  --
  -- Stream is expected to have one component per pixel.  Pixel is lit
  -- when the most significant bit of its component is set, which
  -- makes a one-bit color index stream (e.g. from a colormap
  -- generator with color_count_l2_c = 1) the natural source.
  --
  -- Panel memory takes eight lines at once, so the driver takes eight
  -- lines from the stream into an internal buffer, then sends them
  -- out.  The stream is held while the buffer is sent.
  component ssd1306_spi_driver is
    generic(
      clock_i_hz_c : natural;
      config_c : nsl_video.pixel_stream.config_t;
      spi_hz_c : natural := 10_000_000;

      -- Panel geometry.  Height must be a multiple of page_height_c.
      width_c : positive range 1 to max_width_c := 128;
      height_c : positive range page_height_c to max_height_c := 64;
      -- Controller column the first panel column is wired to.
      column_offset_c : natural range 0 to max_width_c - 1 := 0;
      -- See init_sequence.
      com_alternative_c : boolean := true;
      charge_pump_c : boolean := true;
      rotate_180_c : boolean := false;
      contrast_c : byte := x"8f"
      );
    port(
      clock_i : in std_ulogic;
      reset_n_i : in std_ulogic;

      enable_i : in std_ulogic := '1';
      refresh_i : in std_ulogic := '1';

      -- Connection to display controller
      spi_o : out nsl_spi.spi.spi_slave_i;
      dc_o : out std_ulogic;
      reset_n_o : out std_ulogic;
      -- Panel supply switch (VCC or VBAT, depending on charge pump
      -- usage), asserted after the first frame is sent.
      vcc_en_o : out std_ulogic;
      -- Logic supply switch, asserted first on power-up, last on
      -- power-down.  May be left unconnected when logic supply is not
      -- switchable
      power_en_o : out std_ulogic;

      pixel_i : in nsl_video.pixel_stream.master_t;
      pixel_o : out nsl_video.pixel_stream.slave_t;

      synced_o : out std_ulogic
      );
  end component;

end package;

package body ssd1306 is

  function init_sequence(height: positive;
                         com_alternative: boolean;
                         charge_pump: boolean;
                         rotate_180: boolean;
                         contrast: byte) return byte_string
  is
    variable charge_pump_v, segment_remap_v, com_scan_v, com_pins_v, precharge_v: byte;
    variable ret: byte_string(0 to init_sequence_length_c - 1);
  begin
    assert height mod page_height_c = 0
      report "Panel height must be a multiple of page height"
      severity failure;

    if charge_pump then
      charge_pump_v := cmd_charge_pump_enable;
      precharge_v := x"f1";
    else
      charge_pump_v := cmd_charge_pump_disable;
      precharge_v := x"22";
    end if;

    if rotate_180 then
      segment_remap_v := cmd_segment_remap_off;
      com_scan_v := cmd_com_scan_increasing;
    else
      segment_remap_v := cmd_segment_remap_on;
      com_scan_v := cmd_com_scan_decreasing;
    end if;

    if com_alternative then
      com_pins_v := cmd_com_pins_alternative;
    else
      com_pins_v := cmd_com_pins_sequential;
    end if;

    ret := byte_string'(0 => cmd_display_sleep)
           & cmd_clock_divider & x"80"
           & cmd_multiplex_ratio & to_byte(height - 1)
           & cmd_display_offset & x"00"
           & cmd_display_start_line
           & cmd_charge_pump & charge_pump_v
           & cmd_addressing_mode & cmd_addressing_mode_horizontal
           & segment_remap_v
           & com_scan_v
           & cmd_com_pins & com_pins_v
           & cmd_contrast & contrast
           & cmd_precharge_period & precharge_v
           -- Panel vendor value, out of the controller documented set
           & cmd_vcomh_deselect_level & x"40"
           & cmd_display_normal
           & cmd_display_not_inverted;

    return ret;
  end function;

end package body;
